### ISSUE TITLE
containerning har tomonidan auto margin berilgan

### ISSUE THREAD

**Issue by frontendtester** [Azizbek-Boyhamdamov/AnsorMed#3]
https://github.com/Azizbek-Boyhamdamov/AnsorMed/blob/8dc974a2644275e0613186cb2f3941d31bdffc33/css/style.css#L27

`.container` ning faqat yon tomonlaridan auto margin berish kerak

**Comment by Azizbek-Boyhamdamov** [comment]
buni ham #2 issue tog'irlab ketdim
