### ISSUE TITLE
 <div class="hero-content"> shu  div ni  ichidegi kodlarizga qarab qo`ying

### ISSUE THREAD

**Issue by frontendoniyorbek** [Azizbek-Boyhamdamov/AnsorMed#4]
width berib qo`ysangiz to`g`ri bo`lar edi yozuvlar cho`zilib ketibdi shunga etibor berib qo`ying

**Comment by Azizbek-Boyhamdamov** [comment]
Yozuvlar cho'zilib ketgani yoq, height maketdagi bilan tog'ri kelyabdi chunki margin va font stillar tog'ri ko'rsatilgan.
Bu xolatda aniq height berib bo'lmaydi chunki ekran kichrayganda uning heihgti o'zgarishi mumkin
![height](https://user-images.githubusercontent.com/99174734/155973154-c88747db-6a39-483e-b9c8-921d710bb28f.png)
